### ISSUE TITLE
Python 3.8 : ImportError: cannot import name 'clock' from 'time' 

### ISSUE THREAD

**Issue by codeg8** [timnon/pyschedule#107]
Library not working with Python 3.8 .

**Comment by fderyckel** [comment]
YEs, I am having the same issues.  
It comes from some deprecated libraries. 

"time.clock is a method that has been deprecated since Python 3.3 and removed from Python 3.8 ([see the Python 3.7 time documentation for more information](https://docs.python.org/3.7/library/time.html#time.clock)), because its behaviour was dependent on the platform (it behaved differently on Unix compared to Windows). As the documentation suggests, you should use time.perf_counter() or time.process_time() instead. These are subtly different, see [this Stack Overflow question](https://stackoverflow.com/questions/25785243/understanding-time-perf-counter-and-time-process-time) for more details."
here: https://stackoverflow.com/questions/65499013/importerror-cannot-import-name-clock-from-time-unknown-location

**Comment by onrdmr** [comment]
thank you for reply. Can you change clock function to perf_counter or process_time?
